# Generated by Django 5.1.1 on 2024-10-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokedex_number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("abilities", models.JSONField()),
                ("sprites", models.JSONField()),
                ("types", models.JSONField()),
            ],
        ),
    ]
